<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="TestClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\sqlexpress;Initial Catalog=Test;Integrated Security=True" SettingsObjectName="ConsoleApplication3.Properties.Settings" SettingsPropertyName="TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>